version: "3.7"

services:
  php:
    build:
      context: ./.docker/php
      target: ${ENVIRONMENT-prod}
    volumes:
      - ./:/app
      - ~/.composer:/root/.composer
    environment:
      XDEBUG_CONFIG: client_host=172.17.0.1 client_port=9003 start_with_request=yes
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./:/app
      - ./.docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf