version: "3.7"

services:
  php:
    build:
      context: ./.docker/php
      target: prod
    volumes:
      - ./:/app
      - ~/.composer:/root/.composer
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./:/app
      - ./.docker/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf